sonar.projectKey=Or-Deep777_VendeAi
sonar.organization=or-deep777

sonar.sources=backend/src
sonar.exclusions=**/node_modules/**,**/dist/**,.next/**

sonar.tests=backend
sonar.tests.inclusions=**/*.spect.ts

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info